In [4]:
import pandas as pd

In [6]:
df1 = pd.read_csv("Laliga.csv", header=1)
df1

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
0,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,23,8,8,3,4,79,1929,1929,1
1,2,Barcelona,86,4262,2762,1581,573,608,5900,3114,25,25,12,12,4,6,83,1929,1929,1
2,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,10,8,16,9,7,6,56,1929,2002-03,1
3,4,Valencia,82,3386,2664,1187,616,861,4398,3469,6,6,10,11,10,7,50,1931-32,1987-88,1
4,5,Athletic Bilbao,86,3368,2762,1209,633,920,4631,3700,8,7,10,5,8,10,49,1929,1929,1
5,6,Sevilla,73,2819,2408,990,531,887,3680,3373,1,4,4,5,12,6,32,1934-35,2001-02,1
6,7,Espanyol,82,2792,2626,948,608,1070,3609,3889,-,-,4,5,2,5,16,1929,1994-95,3
7,8,Real Sociedad,70,2573,2302,864,577,861,3228,3230,2,3,2,5,4,3,19,1929,2010-11,1
8,9,Zaragoza,58,2109,1986,698,522,766,2683,2847,-,1,4,5,4,4,18,1939-40,2012-13,2
9,10,Real Betis,51,1884,1728,606,440,682,2159,2492,1,-,2,3,4,4,14,1932-33,2015-16,1
10,11,Deportivo La Coruna,45,1814,1530,563,392,575,2052,2188,1,5,4,1,-,1,12,1941-42,2014-15,1
11,12,Celta Vigo,51,1789,1698,586,389,723,2278,2624,-,-,-,2,4,5,11,1939-40,2012-13,4
12,13,Valladolid,42,1471,1466,463,384,619,1767,2180,-,-,-,1,1,1,3,1948-49,2013-14,4
13,14,Racing Santander,44,1416,1428,453,336,639,1843,2368,-,1,1,2,-,1,5,1929,2011-12,2
14,15,Sporting Gijon,43,1389,1458,471,358,629,1753,2152,-,1,1,2,2,1,7,1944-45,2015-16,2
15,16,Osasuna,37,1351,1318,426,327,565,1500,1834,-,-,-,2,2,2,6,1935-36,2016-17,4
16,17,Malaga,36,1314,1255,390,330,535,1421,1763,-,-,-,1,-,1,2,1949-50,2008-09,4
17,18,Oviedo,38,1174,1192,408,292,492,1642,1951,-,-,3,2,2,4,11,1933-34,2000-01,3
18,19,Mallorca,27,1148,988,333,256,399,1182,1371,-,-,2,-,2,1,5,1960-61,2012-13,3
19,20,Las Palmas,33,1020,1096,367,242,487,1347,1746,-,1,1,1,1,1,5,1951-52,2015-16,2
20,21,Villarreal,17,970,646,266,172,208,892,789,-,1,1,2,3,2,9,1998-99,2013-14,2
21,22,Granada,23,667,742,218,175,349,819,1157,-,-,-,-,-,2,2,1941-42,2016-17,6
22,23,Rayo Vallecano,17,662,652,189,148,305,760,1088,-,-,-,-,-,-,-,1977-78,2015-16,8
23,24,Elche,21,606,678,203,180,295,750,1022,-,-,-,-,1,1,2,1959-60,2014-15,5
24,25,Getafe,12,553,456,147,112,197,520,633,-,-,-,-,-,1,1,2004-05,2015-16,6
25,26,Hercules,20,538,628,184,149,295,716,1050,-,-,-,-,1,4,5,1935-36,2010-11,5
26,27,Tenerife,13,510,494,155,128,211,619,744,-,-,-,-,2,-,2,1961-62,2009-10,5
27,28,Murcia,18,445,586,145,143,298,607,992,-,-,-,-,-,-,-,1940-41,2007-08,11
28,29,Alaves,12,421,380,125,81,174,458,623,-,-,-,-,-,1,1,1930-31,2016-17,6
29,30,Levante,11,416,402,113,95,194,430,632,-,-,-,-,-,1,1,1963-64,2015-16,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31,32,Sabadell,14,353,426,129,95,202,492,720,-,-,-,1,1,-,2,1943-44,1987-88,4
32,33,Cadiz,12,343,448,104,127,217,393,662,-,-,-,-,-,-,-,1977-78,2005-06,12
33,34,Logrones,9,293,346,96,92,158,291,489,-,-,-,-,-,-,-,1987-88,1996-97,7
34,35,Castellon,11,285,334,103,79,152,419,588,-,-,-,1,2,-,3,1941-42,1990-91,4
35,36,Albacete,7,277,270,76,76,118,320,410,-,-,-,-,-,-,-,1991-92,2004-05,7
36,37,Almeria,6,242,228,62,56,110,244,366,-,-,-,-,-,-,-,2007-08,2014-15,8
37,38,Cordoba,9,230,282,82,63,137,285,430,-,-,-,-,1,-,1,1962-63,2014-15,5
38,39,Compostela,4,190,160,52,45,63,199,241,-,-,-,-,-,-,-,1994-95,1997-98,10
39,40,Recreativo,5,188,186,50,46,90,202,296,-,-,-,-,-,-,-,1978-79,2008-09,8
40,41,Burgos CF,6,168,204,59,50,95,216,310,-,-,-,-,-,-,-,1971-72,1979-80,12
41,42,Pontevedra,6,150,180,53,44,83,165,221,-,-,-,-,-,-,-,1963-64,1969-70,7
42,43,Numancia,4,148,152,37,37,78,155,253,-,-,-,-,-,-,-,1999-00,2008-09,17
43,44,Eibar,3,132,114,35,27,52,139,167,-,-,-,-,-,-,-,2014-15,2014-15,10
44,45,Arenas,7,107,130,43,21,66,227,308,-,-,1,-,3,-,4,1929,1934-35,3
45,46,Real Burgos,3,96,114,26,44,44,101,139,-,-,-,-,-,-,-,1990-91,1992-93,9
46,47,Gimnastic,4,91,116,34,16,66,181,295,-,-,-,-,-,-,-,1947-48,2006-07,7
47,48,Extremadura,2,83,80,20,23,37,62,117,-,-,-,-,-,-,-,1996-97,1998-99,17
48,49,Merida,2,81,80,19,24,37,70,115,-,-,-,-,-,-,-,1995-96,1997-98,19
49,50,Alcoyano,4,76,108,30,16,62,145,252,-,-,-,-,-,-,-,1945-46,1950-51,10
50,51,Jaen,3,71,90,29,13,48,121,183,-,-,-,-,-,-,-,1953-54,1957-58,14
51,52,Real Union,4,56,72,21,14,37,153,184,-,-,-,-,-,1,1,1929,1931-32,6
52,53,AD Almeria,2,52,68,17,18,33,71,116,-,-,-,-,-,-,-,1979-80,1980-81,10
53,54,Europa,3,42,54,18,6,30,97,131,-,-,-,-,-,-,-,1929,1930-31,8
54,55,Lleida,2,40,68,13,14,41,70,182,-,-,-,-,-,-,-,1950-51,1993-94,16
55,56,Leganes,1,35,38,8,11,19,36,55,-,-,-,-,-,-,-,2016-17,2016-17,17
56,57,Xerez,1,34,38,8,10,20,38,66,-,-,-,-,-,-,-,2009-10,2009-10,20
57,58,Condal,1,22,30,7,8,15,37,57,-,-,-,-,-,-,-,1956-57,1956-57,16
58,59,Atletico Tetuan,1,19,30,7,5,18,51,85,-,-,-,-,-,-,-,1951-52,1951-52,16
59,60,Cultural Leonesa,1,14,30,5,4,21,34,65,-,-,-,-,-,-,-,1955-56,1955-56,15
60,61,Girona,1,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2017-18,2017-18,9

Read the data set and replace dashes with 0 to make sure you can perform arithmetic operations on the data.

In [7]:
df2 = pd.read_csv("Laliga.csv", header=1, na_values = ["-"])
df2.head(10)

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
0,1,Real Madrid,86,4385.0,2762.0,1647.0,552.0,563.0,5947.0,3140.0,33.0,23.0,8.0,8.0,3.0,4.0,79.0,1929,1929,1
1,2,Barcelona,86,4262.0,2762.0,1581.0,573.0,608.0,5900.0,3114.0,25.0,25.0,12.0,12.0,4.0,6.0,83.0,1929,1929,1
2,3,Atletico Madrid,80,3442.0,2614.0,1241.0,598.0,775.0,4534.0,3309.0,10.0,8.0,16.0,9.0,7.0,6.0,56.0,1929,2002-03,1
3,4,Valencia,82,3386.0,2664.0,1187.0,616.0,861.0,4398.0,3469.0,6.0,6.0,10.0,11.0,10.0,7.0,50.0,1931-32,1987-88,1
4,5,Athletic Bilbao,86,3368.0,2762.0,1209.0,633.0,920.0,4631.0,3700.0,8.0,7.0,10.0,5.0,8.0,10.0,49.0,1929,1929,1
5,6,Sevilla,73,2819.0,2408.0,990.0,531.0,887.0,3680.0,3373.0,1.0,4.0,4.0,5.0,12.0,6.0,32.0,1934-35,2001-02,1
6,7,Espanyol,82,2792.0,2626.0,948.0,608.0,1070.0,3609.0,3889.0,NaN,NaN,4.0,5.0,2.0,5.0,16.0,1929,1994-95,3
7,8,Real Sociedad,70,2573.0,2302.0,864.0,577.0,861.0,3228.0,3230.0,2.0,3.0,2.0,5.0,4.0,3.0,19.0,1929,2010-11,1
8,9,Zaragoza,58,2109.0,1986.0,698.0,522.0,766.0,2683.0,2847.0,NaN,1.0,4.0,5.0,4.0,4.0,18.0,1939-40,2012-13,2
9,10,Real Betis,51,1884.0,1728.0,606.0,440.0,682.0,2159.0,2492.0,1.0,NaN,2.0,3.0,4.0,4.0,14.0,1932-33,2015-16,1

In [8]:
df3 = df2.fillna(0)
df3

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
0,1,Real Madrid,86,4385.0,2762.0,1647.0,552.0,563.0,5947.0,3140.0,33.0,23.0,8.0,8.0,3.0,4.0,79.0,1929,1929,1
1,2,Barcelona,86,4262.0,2762.0,1581.0,573.0,608.0,5900.0,3114.0,25.0,25.0,12.0,12.0,4.0,6.0,83.0,1929,1929,1
2,3,Atletico Madrid,80,3442.0,2614.0,1241.0,598.0,775.0,4534.0,3309.0,10.0,8.0,16.0,9.0,7.0,6.0,56.0,1929,2002-03,1
3,4,Valencia,82,3386.0,2664.0,1187.0,616.0,861.0,4398.0,3469.0,6.0,6.0,10.0,11.0,10.0,7.0,50.0,1931-32,1987-88,1
4,5,Athletic Bilbao,86,3368.0,2762.0,1209.0,633.0,920.0,4631.0,3700.0,8.0,7.0,10.0,5.0,8.0,10.0,49.0,1929,1929,1
5,6,Sevilla,73,2819.0,2408.0,990.0,531.0,887.0,3680.0,3373.0,1.0,4.0,4.0,5.0,12.0,6.0,32.0,1934-35,2001-02,1
6,7,Espanyol,82,2792.0,2626.0,948.0,608.0,1070.0,3609.0,3889.0,0.0,0.0,4.0,5.0,2.0,5.0,16.0,1929,1994-95,3
7,8,Real Sociedad,70,2573.0,2302.0,864.0,577.0,861.0,3228.0,3230.0,2.0,3.0,2.0,5.0,4.0,3.0,19.0,1929,2010-11,1
8,9,Zaragoza,58,2109.0,1986.0,698.0,522.0,766.0,2683.0,2847.0,0.0,1.0,4.0,5.0,4.0,4.0,18.0,1939-40,2012-13,2
9,10,Real Betis,51,1884.0,1728.0,606.0,440.0,682.0,2159.0,2492.0,1.0,0.0,2.0,3.0,4.0,4.0,14.0,1932-33,2015-16,1
10,11,Deportivo La Coruna,45,1814.0,1530.0,563.0,392.0,575.0,2052.0,2188.0,1.0,5.0,4.0,1.0,0.0,1.0,12.0,1941-42,2014-15,1
11,12,Celta Vigo,51,1789.0,1698.0,586.0,389.0,723.0,2278.0,2624.0,0.0,0.0,0.0,2.0,4.0,5.0,11.0,1939-40,2012-13,4
12,13,Valladolid,42,1471.0,1466.0,463.0,384.0,619.0,1767.0,2180.0,0.0,0.0,0.0,1.0,1.0,1.0,3.0,1948-49,2013-14,4
13,14,Racing Santander,44,1416.0,1428.0,453.0,336.0,639.0,1843.0,2368.0,0.0,1.0,1.0,2.0,0.0,1.0,5.0,1929,2011-12,2
14,15,Sporting Gijon,43,1389.0,1458.0,471.0,358.0,629.0,1753.0,2152.0,0.0,1.0,1.0,2.0,2.0,1.0,7.0,1944-45,2015-16,2
15,16,Osasuna,37,1351.0,1318.0,426.0,327.0,565.0,1500.0,1834.0,0.0,0.0,0.0,2.0,2.0,2.0,6.0,1935-36,2016-17,4
16,17,Malaga,36,1314.0,1255.0,390.0,330.0,535.0,1421.0,1763.0,0.0,0.0,0.0,1.0,0.0,1.0,2.0,1949-50,2008-09,4
17,18,Oviedo,38,1174.0,1192.0,408.0,292.0,492.0,1642.0,1951.0,0.0,0.0,3.0,2.0,2.0,4.0,11.0,1933-34,2000-01,3
18,19,Mallorca,27,1148.0,988.0,333.0,256.0,399.0,1182.0,1371.0,0.0,0.0,2.0,0.0,2.0,1.0,5.0,1960-61,2012-13,3
19,20,Las Palmas,33,1020.0,1096.0,367.0,242.0,487.0,1347.0,1746.0,0.0,1.0,1.0,1.0,1.0,1.0,5.0,1951-52,2015-16,2
20,21,Villarreal,17,970.0,646.0,266.0,172.0,208.0,892.0,789.0,0.0,1.0,1.0,2.0,3.0,2.0,9.0,1998-99,2013-14,2
21,22,Granada,23,667.0,742.0,218.0,175.0,349.0,819.0,1157.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,1941-42,2016-17,6
22,23,Rayo Vallecano,17,662.0,652.0,189.0,148.0,305.0,760.0,1088.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1977-78,2015-16,8
23,24,Elche,21,606.0,678.0,203.0,180.0,295.0,750.0,1022.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,1959-60,2014-15,5
24,25,Getafe,12,553.0,456.0,147.0,112.0,197.0,520.0,633.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2004-05,2015-16,6
25,26,Hercules,20,538.0,628.0,184.0,149.0,295.0,716.0,1050.0,0.0,0.0,0.0,0.0,1.0,4.0,5.0,1935-36,2010-11,5
26,27,Tenerife,13,510.0,494.0,155.0,128.0,211.0,619.0,744.0,0.0,0.0,0.0,0.0,2.0,0.0,2.0,1961-62,2009-10,5
27,28,Murcia,18,445.0,586.0,145.0,143.0,298.0,607.0,992.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1940-41,2007-08,11
28,29,Alaves,12,421.0,380.0,125.0,81.0,174.0,458.0,623.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1930-31,2016-17,6
29,30,Levante,11,416.0,402.0,113.0,95.0,194.0,430.0,632.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1963-64,2015-16,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31,32,Sabadell,14,353.0,426.0,129.0,95.0,202.0,492.0,720.0,0.0,0.0,0.0,1.0,1.0,0.0,2.0,1943-44,1987-88,4
32,33,Cadiz,12,343.0,448.0,104.0,127.0,217.0,393.0,662.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1977-78,2005-06,12
33,34,Logrones,9,293.0,346.0,96.0,92.0,158.0,291.0,489.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1987-88,1996-97,7
34,35,Castellon,11,285.0,334.0,103.0,79.0,152.0,419.0,588.0,0.0,0.0,0.0,1.0,2.0,0.0,3.0,1941-42,1990-91,4
35,36,Albacete,7,277.0,270.0,76.0,76.0,118.0,320.0,410.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1991-92,2004-05,7
36,37,Almeria,6,242.0,228.0,62.0,56.0,110.0,244.0,366.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2007-08,2014-15,8
37,38,Cordoba,9,230.0,282.0,82.0,63.0,137.0,285.0,430.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1962-63,2014-15,5
38,39,Compostela,4,190.0,160.0,52.0,45.0,63.0,199.0,241.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1994-95,1997-98,10
39,40,Recreativo,5,188.0,186.0,50.0,46.0,90.0,202.0,296.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1978-79,2008-09,8
40,41,Burgos CF,6,168.0,204.0,59.0,50.0,95.0,216.0,310.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1971-72,1979-80,12
41,42,Pontevedra,6,150.0,180.0,53.0,44.0,83.0,165.0,221.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1963-64,1969-70,7
42,43,Numancia,4,148.0,152.0,37.0,37.0,78.0,155.0,253.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1999-00,2008-09,17
43,44,Eibar,3,132.0,114.0,35.0,27.0,52.0,139.0,167.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2014-15,2014-15,10
44,45,Arenas,7,107.0,130.0,43.0,21.0,66.0,227.0,308.0,0.0,0.0,1.0,0.0,3.0,0.0,4.0,1929,1934-35,3
45,46,Real Burgos,3,96.0,114.0,26.0,44.0,44.0,101.0,139.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1990-91,1992-93,9
46,47,Gimnastic,4,91.0,116.0,34.0,16.0,66.0,181.0,295.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1947-48,2006-07,7
47,48,Extremadura,2,83.0,80.0,20.0,23.0,37.0,62.0,117.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1996-97,1998-99,17
48,49,Merida,2,81.0,80.0,19.0,24.0,37.0,70.0,115.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1995-96,1997-98,19
49,50,Alcoyano,4,76.0,108.0,30.0,16.0,62.0,145.0,252.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1945-46,1950-51,10
50,51,Jaen,3,71.0,90.0,29.0,13.0,48.0,121.0,183.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1953-54,1957-58,14
51,52,Real Union,4,56.0,72.0,21.0,14.0,37.0,153.0,184.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1929,1931-32,6
52,53,AD Almeria,2,52.0,68.0,17.0,18.0,33.0,71.0,116.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1979-80,1980-81,10
53,54,Europa,3,42.0,54.0,18.0,6.0,30.0,97.0,131.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1929,1930-31,8
54,55,Lleida,2,40.0,68.0,13.0,14.0,41.0,70.0,182.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1950-51,1993-94,16
55,56,Leganes,1,35.0,38.0,8.0,11.0,19.0,36.0,55.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2016-17,2016-17,17
56,57,Xerez,1,34.0,38.0,8.0,10.0,20.0,38.0,66.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2009-10,2009-10,20
57,58,Condal,1,22.0,30.0,7.0,8.0,15.0,37.0,57.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1956-57,1956-57,16
58,59,Atletico Tetuan,1,19.0,30.0,7.0,5.0,18.0,51.0,85.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1951-52,1951-52,16
59,60,Cultural Leonesa,1,14.0,30.0,5.0,4.0,21.0,34.0,65.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1955-56,1955-56,15
60,61,Girona,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2017-18,2017-18,9

Print all the teams which have started playing between 1930-1980.

In [35]:
pd.to_datetime(df3.Debut, errors='ignore')
df3.head()

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
0,1,Real Madrid,86,4385.0,2762.0,1647.0,552.0,563.0,5947.0,3140.0,33.0,23.0,8.0,8.0,3.0,4.0,79.0,1929,1929,1
1,2,Barcelona,86,4262.0,2762.0,1581.0,573.0,608.0,5900.0,3114.0,25.0,25.0,12.0,12.0,4.0,6.0,83.0,1929,1929,1
2,3,Atletico Madrid,80,3442.0,2614.0,1241.0,598.0,775.0,4534.0,3309.0,10.0,8.0,16.0,9.0,7.0,6.0,56.0,1929,2002-03,1
3,4,Valencia,82,3386.0,2664.0,1187.0,616.0,861.0,4398.0,3469.0,6.0,6.0,10.0,11.0,10.0,7.0,50.0,1931-32,1987-88,1
4,5,Athletic Bilbao,86,3368.0,2762.0,1209.0,633.0,920.0,4631.0,3700.0,8.0,7.0,10.0,5.0,8.0,10.0,49.0,1929,1929,1

In [37]:
new_df = df3.loc[(df3['Debut'] >= '1930') & (df3['Debut'] <= '1980')]
new_df.Debut

3     1931-32
5     1934-35
8     1939-40
9     1932-33
10    1941-42
11    1939-40
12    1948-49
14    1944-45
15    1935-36
16    1949-50
17    1933-34
18    1960-61
19    1951-52
21    1941-42
22    1977-78
23    1959-60
25    1935-36
26    1961-62
27    1940-41
28    1930-31
29    1963-64
30    1974-75
31    1943-44
32    1977-78
34    1941-42
37    1962-63
39    1978-79
40    1971-72
41    1963-64
46    1947-48
49    1945-46
50    1953-54
52    1979-80
54    1950-51
57    1956-57
58    1951-52
59    1955-56
Name: Debut, dtype: object

Print the list of teams which came Top 5 in terms of points

In [82]:
df3.head()  # the data is already in sorting order with respect to "Points" column.

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,...,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition,goal difference,Winning Percent
0,1,Real Madrid,86,4385.0,2762.0,1647.0,552.0,563.0,5947.0,3140.0,...,8.0,8.0,3.0,4.0,79.0,1929,1929,1,2807.0,59.630702
1,2,Barcelona,86,4262.0,2762.0,1581.0,573.0,608.0,5900.0,3114.0,...,12.0,12.0,4.0,6.0,83.0,1929,1929,1,2786.0,57.241130
2,3,Atletico Madrid,80,3442.0,2614.0,1241.0,598.0,775.0,4534.0,3309.0,...,16.0,9.0,7.0,6.0,56.0,1929,2002-03,1,1225.0,47.475134
3,4,Valencia,82,3386.0,2664.0,1187.0,616.0,861.0,4398.0,3469.0,...,10.0,11.0,10.0,7.0,50.0,1931-32,1987-88,1,929.0,44.557057
4,5,Athletic Bilbao,86,3368.0,2762.0,1209.0,633.0,920.0,4631.0,3700.0,...,10.0,5.0,8.0,10.0,49.0,1929,1929,1,931.0,43.772629

Write a function with name “Goal_diff_count” which should return all the teams with their Goal Differences. Using the same function, find the team which has maximum and minimum goal difference.

In [39]:
def Goal_diff_count(goalsFor, goalsAgainst):
    return goalsFor - goalsAgainst

In [42]:
Goal_diff_count(df3.GoalsFor, df3.GoalsAgainst).max()

2807.0

In [57]:
Goal_diff_count(df3.GoalsFor, df3.GoalsAgainst).min()

-525.0

In [44]:
df5 = df3

In [46]:
df5.head(10)

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,...,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition,goal difference
0,1,Real Madrid,86,4385.0,2762.0,1647.0,552.0,563.0,5947.0,3140.0,...,23.0,8.0,8.0,3.0,4.0,79.0,1929,1929,1,2807.0
1,2,Barcelona,86,4262.0,2762.0,1581.0,573.0,608.0,5900.0,3114.0,...,25.0,12.0,12.0,4.0,6.0,83.0,1929,1929,1,2786.0
2,3,Atletico Madrid,80,3442.0,2614.0,1241.0,598.0,775.0,4534.0,3309.0,...,8.0,16.0,9.0,7.0,6.0,56.0,1929,2002-03,1,1225.0
3,4,Valencia,82,3386.0,2664.0,1187.0,616.0,861.0,4398.0,3469.0,...,6.0,10.0,11.0,10.0,7.0,50.0,1931-32,1987-88,1,929.0
4,5,Athletic Bilbao,86,3368.0,2762.0,1209.0,633.0,920.0,4631.0,3700.0,...,7.0,10.0,5.0,8.0,10.0,49.0,1929,1929,1,931.0
5,6,Sevilla,73,2819.0,2408.0,990.0,531.0,887.0,3680.0,3373.0,...,4.0,4.0,5.0,12.0,6.0,32.0,1934-35,2001-02,1,307.0
6,7,Espanyol,82,2792.0,2626.0,948.0,608.0,1070.0,3609.0,3889.0,...,0.0,4.0,5.0,2.0,5.0,16.0,1929,1994-95,3,-280.0
7,8,Real Sociedad,70,2573.0,2302.0,864.0,577.0,861.0,3228.0,3230.0,...,3.0,2.0,5.0,4.0,3.0,19.0,1929,2010-11,1,-2.0
8,9,Zaragoza,58,2109.0,1986.0,698.0,522.0,766.0,2683.0,2847.0,...,1.0,4.0,5.0,4.0,4.0,18.0,1939-40,2012-13,2,-164.0
9,10,Real Betis,51,1884.0,1728.0,606.0,440.0,682.0,2159.0,2492.0,...,0.0,2.0,3.0,4.0,4.0,14.0,1932-33,2015-16,1,-333.0

Create a new column with name “Winning Percent” and append it to the data set

In [60]:
df5["Winning Percent"] = (df5.GamesWon / df5.GamesPlayed) * 100

In [80]:
df5

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,...,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition,goal difference,Winning Percent
0,1,Real Madrid,86,4385.0,2762.0,1647.0,552.0,563.0,5947.0,3140.0,...,8.0,8.0,3.0,4.0,79.0,1929,1929,1,2807.0,59.630702
1,2,Barcelona,86,4262.0,2762.0,1581.0,573.0,608.0,5900.0,3114.0,...,12.0,12.0,4.0,6.0,83.0,1929,1929,1,2786.0,57.241130
2,3,Atletico Madrid,80,3442.0,2614.0,1241.0,598.0,775.0,4534.0,3309.0,...,16.0,9.0,7.0,6.0,56.0,1929,2002-03,1,1225.0,47.475134
3,4,Valencia,82,3386.0,2664.0,1187.0,616.0,861.0,4398.0,3469.0,...,10.0,11.0,10.0,7.0,50.0,1931-32,1987-88,1,929.0,44.557057
4,5,Athletic Bilbao,86,3368.0,2762.0,1209.0,633.0,920.0,4631.0,3700.0,...,10.0,5.0,8.0,10.0,49.0,1929,1929,1,931.0,43.772629
5,6,Sevilla,73,2819.0,2408.0,990.0,531.0,887.0,3680.0,3373.0,...,4.0,5.0,12.0,6.0,32.0,1934-35,2001-02,1,307.0,41.112957
6,7,Espanyol,82,2792.0,2626.0,948.0,608.0,1070.0,3609.0,3889.0,...,4.0,5.0,2.0,5.0,16.0,1929,1994-95,3,-280.0,36.100533
7,8,Real Sociedad,70,2573.0,2302.0,864.0,577.0,861.0,3228.0,3230.0,...,2.0,5.0,4.0,3.0,19.0,1929,2010-11,1,-2.0,37.532580
8,9,Zaragoza,58,2109.0,1986.0,698.0,522.0,766.0,2683.0,2847.0,...,4.0,5.0,4.0,4.0,18.0,1939-40,2012-13,2,-164.0,35.146022
9,10,Real Betis,51,1884.0,1728.0,606.0,440.0,682.0,2159.0,2492.0,...,2.0,3.0,4.0,4.0,14.0,1932-33,2015-16,1,-333.0,35.069444
10,11,Deportivo La Coruna,45,1814.0,1530.0,563.0,392.0,575.0,2052.0,2188.0,...,4.0,1.0,0.0,1.0,12.0,1941-42,2014-15,1,-136.0,36.797386
11,12,Celta Vigo,51,1789.0,1698.0,586.0,389.0,723.0,2278.0,2624.0,...,0.0,2.0,4.0,5.0,11.0,1939-40,2012-13,4,-346.0,34.511190
12,13,Valladolid,42,1471.0,1466.0,463.0,384.0,619.0,1767.0,2180.0,...,0.0,1.0,1.0,1.0,3.0,1948-49,2013-14,4,-413.0,31.582538
13,14,Racing Santander,44,1416.0,1428.0,453.0,336.0,639.0,1843.0,2368.0,...,1.0,2.0,0.0,1.0,5.0,1929,2011-12,2,-525.0,31.722689
14,15,Sporting Gijon,43,1389.0,1458.0,471.0,358.0,629.0,1753.0,2152.0,...,1.0,2.0,2.0,1.0,7.0,1944-45,2015-16,2,-399.0,32.304527
15,16,Osasuna,37,1351.0,1318.0,426.0,327.0,565.0,1500.0,1834.0,...,0.0,2.0,2.0,2.0,6.0,1935-36,2016-17,4,-334.0,32.321700
16,17,Malaga,36,1314.0,1255.0,390.0,330.0,535.0,1421.0,1763.0,...,0.0,1.0,0.0,1.0,2.0,1949-50,2008-09,4,-342.0,31.075697
17,18,Oviedo,38,1174.0,1192.0,408.0,292.0,492.0,1642.0,1951.0,...,3.0,2.0,2.0,4.0,11.0,1933-34,2000-01,3,-309.0,34.228188
18,19,Mallorca,27,1148.0,988.0,333.0,256.0,399.0,1182.0,1371.0,...,2.0,0.0,2.0,1.0,5.0,1960-61,2012-13,3,-189.0,33.704453
19,20,Las Palmas,33,1020.0,1096.0,367.0,242.0,487.0,1347.0,1746.0,...,1.0,1.0,1.0,1.0,5.0,1951-52,2015-16,2,-399.0,33.485401
20,21,Villarreal,17,970.0,646.0,266.0,172.0,208.0,892.0,789.0,...,1.0,2.0,3.0,2.0,9.0,1998-99,2013-14,2,103.0,41.176471
21,22,Granada,23,667.0,742.0,218.0,175.0,349.0,819.0,1157.0,...,0.0,0.0,0.0,2.0,2.0,1941-42,2016-17,6,-338.0,29.380054
22,23,Rayo Vallecano,17,662.0,652.0,189.0,148.0,305.0,760.0,1088.0,...,0.0,0.0,0.0,0.0,0.0,1977-78,2015-16,8,-328.0,28.987730
23,24,Elche,21,606.0,678.0,203.0,180.0,295.0,750.0,1022.0,...,0.0,0.0,1.0,1.0,2.0,1959-60,2014-15,5,-272.0,29.941003
24,25,Getafe,12,553.0,456.0,147.0,112.0,197.0,520.0,633.0,...,0.0,0.0,0.0,1.0,1.0,2004-05,2015-16,6,-113.0,32.236842
25,26,Hercules,20,538.0,628.0,184.0,149.0,295.0,716.0,1050.0,...,0.0,0.0,1.0,4.0,5.0,1935-36,2010-11,5,-334.0,29.299363
26,27,Tenerife,13,510.0,494.0,155.0,128.0,211.0,619.0,744.0,...,0.0,0.0,2.0,0.0,2.0,1961-62,2009-10,5,-125.0,31.376518
27,28,Murcia,18,445.0,586.0,145.0,143.0,298.0,607.0,992.0,...,0.0,0.0,0.0,0.0,0.0,1940-41,2007-08,11,-385.0,24.744027
28,29,Alaves,12,421.0,380.0,125.0,81.0,174.0,458.0,623.0,...,0.0,0.0,0.0,1.0,1.0,1930-31,2016-17,6,-165.0,32.894737
29,30,Levante,11,416.0,402.0,113.0,95.0,194.0,430.0,632.0,...,0.0,0.0,0.0,1.0,1.0,1963-64,2015-16,6,-202.0,28.109453
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31,32,Sabadell,14,353.0,426.0,129.0,95.0,202.0,492.0,720.0,...,0.0,1.0,1.0,0.0,2.0,1943-44,1987-88,4,-228.0,30.281690
32,33,Cadiz,12,343.0,448.0,104.0,127.0,217.0,393.0,662.0,...,0.0,0.0,0.0,0.0,0.0,1977-78,2005-06,12,-269.0,23.214286
33,34,Logrones,9,293.0,346.0,96.0,92.0,158.0,291.0,489.0,...,0.0,0.0,0.0,0.0,0.0,1987-88,1996-97,7,-198.0,27.745665
34,35,Castellon,11,285.0,334.0,103.0,79.0,152.0,419.0,588.0,...,0.0,1.0,2.0,0.0,3.0,1941-42,1990-91,4,-169.0,30.838323
35,36,Albacete,7,277.0,270.0,76.0,76.0,118.0,320.0,410.0,...,0.0,0.0,0.0,0.0,0.0,1991-92,2004-05,7,-90.0,28.148148
36,37,Almeria,6,242.0,228.0,62.0,56.0,110.0,244.0,366.0,...,0.0,0.0,0.0,0.0,0.0,2007-08,2014-15,8,-122.0,27.192982
37,38,Cordoba,9,230.0,282.0,82.0,63.0,137.0,285.0,430.0,...,0.0,0.0,1.0,0.0,1.0,1962-63,2014-15,5,-145.0,29.078014
38,39,Compostela,4,190.0,160.0,52.0,45.0,63.0,199.0,241.0,...,0.0,0.0,0.0,0.0,0.0,1994-95,1997-98,10,-42.0,32.500000
39,40,Recreativo,5,188.0,186.0,50.0,46.0,90.0,202.0,296.0,...,0.0,0.0,0.0,0.0,0.0,1978-79,2008-09,8,-94.0,26.881720
40,41,Burgos CF,6,168.0,204.0,59.0,50.0,95.0,216.0,310.0,...,0.0,0.0,0.0,0.0,0.0,1971-72,1979-80,12,-94.0,28.921569
41,42,Pontevedra,6,150.0,180.0,53.0,44.0,83.0,165.0,221.0,...,0.0,0.0,0.0,0.0,0.0,1963-64,1969-70,7,-56.0,29.444444
42,43,Numancia,4,148.0,152.0,37.0,37.0,78.0,155.0,253.0,...,0.0,0.0,0.0,0.0,0.0,1999-00,2008-09,17,-98.0,24.342105
43,44,Eibar,3,132.0,114.0,35.0,27.0,52.0,139.0,167.0,...,0.0,0.0,0.0,0.0,0.0,2014-15,2014-15,10,-28.0,30.701754
44,45,Arenas,7,107.0,130.0,43.0,21.0,66.0,227.0,308.0,...,1.0,0.0,3.0,0.0,4.0,1929,1934-35,3,-81.0,33.076923
45,46,Real Burgos,3,96.0,114.0,26.0,44.0,44.0,101.0,139.0,...,0.0,0.0,0.0,0.0,0.0,1990-91,1992-93,9,-38.0,22.807018
46,47,Gimnastic,4,91.0,116.0,34.0,16.0,66.0,181.0,295.0,...,0.0,0.0,0.0,0.0,0.0,1947-48,2006-07,7,-114.0,29.310345
47,48,Extremadura,2,83.0,80.0,20.0,23.0,37.0,62.0,117.0,...,0.0,0.0,0.0,0.0,0.0,1996-97,1998-99,17,-55.0,25.000000
48,49,Merida,2,81.0,80.0,19.0,24.0,37.0,70.0,115.0,...,0.0,0.0,0.0,0.0,0.0,1995-96,1997-98,19,-45.0,23.750000
49,50,Alcoyano,4,76.0,108.0,30.0,16.0,62.0,145.0,252.0,...,0.0,0.0,0.0,0.0,0.0,1945-46,1950-51,10,-107.0,27.777778
50,51,Jaen,3,71.0,90.0,29.0,13.0,48.0,121.0,183.0,...,0.0,0.0,0.0,0.0,0.0,1953-54,1957-58,14,-62.0,32.222222
51,52,Real Union,4,56.0,72.0,21.0,14.0,37.0,153.0,184.0,...,0.0,0.0,0.0,1.0,1.0,1929,1931-32,6,-31.0,29.166667
52,53,AD Almeria,2,52.0,68.0,17.0,18.0,33.0,71.0,116.0,...,0.0,0.0,0.0,0.0,0.0,1979-80,1980-81,10,-45.0,25.000000
53,54,Europa,3,42.0,54.0,18.0,6.0,30.0,97.0,131.0,...,0.0,0.0,0.0,0.0,0.0,1929,1930-31,8,-34.0,33.333333
54,55,Lleida,2,40.0,68.0,13.0,14.0,41.0,70.0,182.0,...,0.0,0.0,0.0,0.0,0.0,1950-51,1993-94,16,-112.0,19.117647
55,56,Leganes,1,35.0,38.0,8.0,11.0,19.0,36.0,55.0,...,0.0,0.0,0.0,0.0,0.0,2016-17,2016-17,17,-19.0,21.052632
56,57,Xerez,1,34.0,38.0,8.0,10.0,20.0,38.0,66.0,...,0.0,0.0,0.0,0.0,0.0,2009-10,2009-10,20,-28.0,21.052632
57,58,Condal,1,22.0,30.0,7.0,8.0,15.0,37.0,57.0,...,0.0,0.0,0.0,0.0,0.0,1956-57,1956-57,16,-20.0,23.333333
58,59,Atletico Tetuan,1,19.0,30.0,7.0,5.0,18.0,51.0,85.0,...,0.0,0.0,0.0,0.0,0.0,1951-52,1951-52,16,-34.0,23.333333
59,60,Cultural Leonesa,1,14.0,30.0,5.0,4.0,21.0,34.0,65.0,...,0.0,0.0,0.0,0.0,0.0,1955-56,1955-56,15,-31.0,16.666667
60,61,Girona,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2017-18,2017-18,9,0.0,NaN

Print the top 5 teams which has the highest Winning percentage

In [83]:
df6 = df5.sort_values(by="Winning Percent", ascending=False)
df6.head()

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,...,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition,goal difference,Winning Percent
0,1,Real Madrid,86,4385.0,2762.0,1647.0,552.0,563.0,5947.0,3140.0,...,8.0,8.0,3.0,4.0,79.0,1929,1929,1,2807.0,59.630702
1,2,Barcelona,86,4262.0,2762.0,1581.0,573.0,608.0,5900.0,3114.0,...,12.0,12.0,4.0,6.0,83.0,1929,1929,1,2786.0,57.241130
2,3,Atletico Madrid,80,3442.0,2614.0,1241.0,598.0,775.0,4534.0,3309.0,...,16.0,9.0,7.0,6.0,56.0,1929,2002-03,1,1225.0,47.475134
3,4,Valencia,82,3386.0,2664.0,1187.0,616.0,861.0,4398.0,3469.0,...,10.0,11.0,10.0,7.0,50.0,1931-32,1987-88,1,929.0,44.557057
4,5,Athletic Bilbao,86,3368.0,2762.0,1209.0,633.0,920.0,4631.0,3700.0,...,10.0,5.0,8.0,10.0,49.0,1929,1929,1,931.0,43.772629

Group teams based on their “Best position” and print the sum of their points for all positions

In [84]:
df5.groupby("BestPosition")[["Points"]].sum()

               Points
BestPosition
1             27933.0
2              6904.0
3              5221.0
4              6563.0
5              1884.0
6              2113.0
7              1186.0
8              1134.0
9                96.0
10              450.0
11              445.0
12              511.0
14               71.0
15               14.0
16               81.0
17              266.0
19               81.0
20               34.0